### ISSUE TITLE
Backup of e-mails fail (partially)

### ISSUE THREAD

**Issue by woosting** [SomethingWithHorizons/mailserver#2]
### Description
New data (originating from new server environment) is not taken into account by external backups that are not made by root (old migrated data _is_ in the backup).

### Workaround
- Manually make a tar of `/var/vmail` and store it on another location periodically.
- Manually [make a tar of the whole container](https://github.com/woosting/linux-notes/blob/master/contents/lxc/migration.md) (if containerized).

### Root-cause
ASSUMPTION: Non-matching user-rights : New e-mails / folders etc. seem to get stored with user permissions `700` (rwx------) for user (i.e.: vmail/5000) only. This means that another user in another container (in this case `woosting`) can not read the data / can not backup it.

### Proposed solution
Make vmail `755` recursively (any security implications?)?

**Comment by kusozayka** [comment]
1. I would recommend to create backups as `root`. This way you'll never have to run into issues like these. It also gives you an advantage you can create multi-user backups.
2. I wouldn't make the the `/var/vmail` directoy 755/775 because of the security implications (as in, the folder would be world readable by anyone who has access to the machine). Beside this, you also have to implement a way within dovecot/postfix to write with such uid/gid. Which can be tricky/unsupported by the software itself, meaning you'll have to work with stickybits. 
3. If you'd prefer single-user backups than I would suggest to change the `uid`/`gid` as defined in the `users` table of the `mailserver` database. The defaults are uid `5000` with gid `5000`, this can be changed on the fly with the uid/gid which is being used for backupping. When this option is chosen, make sure the `chown` the `/var/vmail/domain.tld/user@domain.tld` directory straight away.

**Comment by woosting** [comment]
Closing the issue with 3 solution options for this case.
